name: Test Golang
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -l
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1"
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
        with:
          pulumi-version: 2.16.2
      - run: pulumi login --local
      - run: pulumi stack init dev
      - uses: pulumi/actions@add-basics
        if: always()
        with:
          command: preview
          stack-name: dev
          cwd: ./golang/
