name: Test Golang
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -l
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1"
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
        with:
          pulumi-version: 2.16.2
      - run: pulumi login --local
        working-directory: golang/
      - run: pulumi stack init dev
        working-directory: golang/
        env:
          PULUMI_CONFIG_PASSPHRASE: not-a-secret
      - uses: pulumi/actions@master
        if: always()
        env:
          PULUMI_CONFIG_PASSPHRASE: not-a-secret
        with:
          command: preview
          stack-name: dev
          work-dir: ./golang
  up:
    name: Up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -l
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1"
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
        with:
          pulumi-version: 2.16.2
      - run: pulumi login --local
        working-directory: golang/
      - run: pulumi stack init dev
        working-directory: golang/
        env:
          PULUMI_CONFIG_PASSPHRASE: not-a-secret
      - uses: pulumi/actions@master
        if: always()
        env:
          PULUMI_CONFIG_PASSPHRASE: not-a-secret
        with:
          command: up
          stack-name: dev
          work-dir: ./golang
  refresh:
    name: Refresh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -l
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1"
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
        with:
          pulumi-version: 2.16.2
      - run: pulumi login --local
        working-directory: golang/
      - run: pulumi stack init dev
        working-directory: golang/
        env:
          PULUMI_CONFIG_PASSPHRASE: not-a-secret
      - uses: pulumi/actions@master
        if: always()
        env:
          PULUMI_CONFIG_PASSPHRASE: not-a-secret
        with:
          command: refresh
          stack-name: dev
          work-dir: ./golang
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -l
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1"
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
        with:
          pulumi-version: 2.16.2
      - run: pulumi login --local
        working-directory: golang/
      - run: pulumi stack init dev
        working-directory: golang/
        env:
          PULUMI_CONFIG_PASSPHRASE: not-a-secret
      - uses: pulumi/actions@master
        if: always()
        env:
          PULUMI_CONFIG_PASSPHRASE: not-a-secret
        with:
          command: destroy
          stack-name: dev
          work-dir: ./golang
  wrong-config:
    name: Config Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -l
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1"
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
        with:
          pulumi-version: 2.16.2
      - run: pulumi login --local
        working-directory: golang/
      - run: pulumi stack init dev
        working-directory: golang/
        env:
          PULUMI_CONFIG_PASSPHRASE: not-a-secret
      - uses: pulumi/actions@master
        if: always()
        env:
          PULUMI_CONFIG_PASSPHRASE: not-a-secret
        with:
          command: no-exist
          stack-name: dev
          work-dir: ./golang
