name: Test Repository Dispatch Events
on:
  repository_dispatch:
    types:
      - "test-1"
      - "test-2"
      - "test-3"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.action == 'test-1'
        run: echo "Running from test-1"
      - if: github.event.action == 'test-2'
        run: echo "Running from test-2"
      - if: github.event.action == 'test-3'
        run: echo "Running from test-3"
